NodeManager.Web/ViewComponents/TagsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using NodeManager.Web.Models;
using System.Linq;
//using NodeManager.Domain;
using NodeManager.Web.DBInfrastucture;
using NodeManager.Web.Abstract;

namespace NodeManager.Web.ViewComponents
{
    [ViewComponent(Name = "Tags")]
    public class TagsViewComponent : ViewComponent
    {
        INodes repos;

        public TagsViewComponent(INodes r)
        {
            repos = r;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new TagsModel();
            model.Tags = repos.Tags.Select(x => x.Value).ToList();
            return View("Index", model);
        }
    }
}

NodeManager.Web/ViewComponents/UploadViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using NodeManager.Web.Models;
using System.Linq;
//using NodeManager.Domain;
using NodeManager.Web.DBInfrastucture;
using NodeManager.Web.Abstract;

namespace NodeManager.Web.ViewComponents
{
    [ViewComponent(Name = "Upload")]
    public class UploadViewComponent : ViewComponent
    {
        INodes repos;

        public UploadViewComponent(INodes r)
        {
            repos = r;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new NodesViewModel();
            return View("Upload", model);
        }
    }
}

NodeManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Менеджер узлов</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css"  rel="stylesheet"/>
</head>
<body>
    <input type="checkbox" id="nav-toggle" hidden>
    <main class="main_container">
        <header class="main_header">
            <!-- Yandex.Metrika counter -->
            <script type="text/javascript">
                (function (m, e, t, r, i, k, a) {
                    m[i] = m[i]  function () { (m[i].a = m[i].a  []).push(arguments) };
                    m[i].l = 1 * new Date();
                    for (var j = 0; j < document.scripts.length; j++) { if (document.scripts[j].src === r) { return; } }
                    k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
                })
                    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

                ym(91761379, "init", {
                    clickmap: true,
                    trackLinks: true,
                    accurateTrackBounce: true
                });
                ym(91761180, "init", {
                    clickmap: true,
                    trackLinks: true,
                    accurateTrackBounce: true,
                    webvisor: true
                });
            </script>
            <noscript><div><img src="https://mc.yandex.ru/watch/91761180" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
            <!-- /Yandex.Metrika counter -->

            <h5 class="nameForMain">Узлы предоставлены для обязательной адаптации к проекту</h5>
            <div class="button_group_left">
                <button class="b_back" onclick="window.history.back()" title="Назад"><span class="fa-solid fa-arrow-left"></span></button>
                @*@await Component.InvokeAsync("Upload")*@
                @if (Model.UserName != null && Model.Role == 1)
                {
                    <form asp-action="AddFile" asp-controller="Node" method="post" enctype="multipart/form-data" class="formLeft upload-file__wrapper">
                        <input type="file" name="uploadedFile" id="uploadedFile" class="upload-file__input" />
                        <label class="upload-file__label" for="uploadedFile">
                            <span class="upload-file__text" title="Загрузить файл/проект">Загрузить файл/проект</span>
                        </label>
                        <button class="subFile" type="submit" title="Загрузить файл/проект"><span class="fa-solid fa-upload"></span></button>
                    </form>
                }
            </div>

            <div class="search_name">
                <form  method="post" class="subscription">
                    <input type="text" placeholder="Введите название" class="search_by_name">
                    <button class="b_search_name" type="submit"><span class="fa fa-search"></span></button>
                </form>
            </div>

            <div class="user">
                <button class="but_user"><span class="fa-solid fa-user"></span></button>
                <div class="user_info">
                    <p>@Model.UserName</p>
                    @if (Model.UserName == null)
                    {
                        @Html.ActionLink("Войти","Login","Account")
                        @Html.ActionLink("Зарегистрироваться","Register","Account")
                    }
                    else {
                        @Html.ActionLink("Выйти","Logout","Account")
                    }
                </div>
            </div>

            <div class="filters_panel">
                <!-- input нужен для того, что бы в дальнейшем задать стили иконке ☰ по событию checked, то есть когда меню будем открыать и закрыать -->
                <input type="checkbox" id="hmt" class="hidden-menu-ticker">
                <!-- Далее вёрстка самой иконки. Разделена на спаны, что бы красиво превращать в крестик при открытии (почти как в Телеграме :) -->
                <label class="btn-menu" for="hmt" title="Панель фильтров">
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                </label>
                <!-- Менюшка раскрывающаяся и скрывающаяся -->
                <ul class="hidden-menu">
                    <li class="first_point">
                        <div class="search_tag">
                            @await Component.InvokeAsync("Tags")
                        </div>
                    </li>
                </ul>
            </div>
        </header>
        <div class="main_content">
                @RenderBody()
        </div>
    </main>
    <script>
        //    window.addEventListener('beforeunload', function (e) {
        //    console.log("I'm here");
        //    $.ajax({
        //        type: "POST",
        //        url: "/Node/List",
        //        async: false
        //    });
        //    console.log(e);
 
        //    e.preventDefault();
        //    var cm = '';
        //    (e || window.event).returnValue = cm;
        //    return cm;
        //}, false);
    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
     <!-- Bootstrap CSS (Cloudflare CDN) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/css/bootstrap.min.css" integrity="sha512-T584yQ/tdRR5QwOpfvDfVQUidzfgc2339Lc8uBDtcp/wYu80d7jwBgAxbyMh0a9YM9F8N3tdErpFI8iaGx6x5g==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <!-- Bootstrap Bundle JS (Cloudflare CDN) -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.min.js" integrity="sha512-UR25UO94eTnCVwjbXozyeVd6ZqpaAE9naiEUBK/A+QDbfSTQFhPGj5lOR6d8tsgbBk84Ggb5A3EkjsOgPRPcKA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>